### PR TITLE
Remove members section

### PR DESCRIPTION
**Pull request by cheshire137**

### CODE REVIEW

**Comment by summasmiff** [comment]
code looks good but I'll leave the decision to the board

**Comment by cheshire137** [comment]
@jbonewits "I vote for getting rid of the member info"

**Comment by wenarcher** [comment]
Hello, Sarah:

Just heard you are going to leave for a new position. I am really happy for
you!

Stay in touch and wish you the best at your new position!


Best regards,
Wen

On Mon, Dec 14, 2015 at 2:17 PM, Sarah Vessels <notifications@github.com>
wrote:

> Merged #27
> <https://github.com/LexLadiesCode/LexLadiesCode.github.io/pull/27>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/LexLadiesCode/LexLadiesCode.github.io/pull/27#event-491365187>
> .
>



-- 
Best regards,

Wen

**Comment by cheshire137** [comment]
Thanks Wen! :)

**Comment by apple888** [comment]
Hi Sarah,
I just see the message about you are going to leave for your new position. congratulations!
Lena

**Comment by melody0202** [comment]
I got on slack but I guess I can't see previous messages.  where is the
meeting tonight?

**Comment by summasmiff** [comment]
No hack night tonight! We're having a board meeting

**Comment by melody0202** [comment]
twilightreverie0202 has sent you a message via Generosity about the Ask the Knight foundation to fund MESO! fundraiser.

Hi there,
I'm reaching out to ask for your support for the "Ask the Knight foundation to fund MESO!" fundraiser on Generosity.
There are a few ways to help:
1. Donate - Everything helps. Even small donations have a big impact.
2. Post to Facebook - The more people who hear about us, the more likely we are to meet our target.
3. Share with your community - Call your friends, tell your co-workers, make an announcement at your organization's event to spread the word.
Generosity has zero platform fees, so your donation goes farther to help us reach our goal.
Thank you!
twilightreverie0202


Help the "Ask the Knight foundation to fund MESO!" fundraiser reach its goal today!

**Pull request merged**
